import React from "react";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider"

import "../globals.css";
import { cn } from "@/lib/utils";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={cn(font.className, "bg-white dark:bg-[#000000] pt-10")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey='minglee-theme'>
        {children}
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}